import React from 'react';
import Link from 'next/link';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { FAQAccordion } from '@/components/FAQAccordion';
import { RelatedGuides } from '@/components/RelatedGuides';
import { ShareButtons } from '@/components/ShareButtons';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { FAQItem } from '@/lib/types';
import { getHreflangAlternates } from '@/i18n/locale-utils';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Clean My Speaker FAQ – Water Eject & Audio Help',
  description:
    'Frequently asked questions about how to clean my speaker, fix my speaker, and fix clean my speaker sound with 165 Hz water eject tones on iPhone & Android.',
  alternates: {
    canonical: 'https://cleanmyspeaker.net/faq/',
    languages: getHreflangAlternates('/faq'),
  },
  openGraph: {
    title: 'Clean My Speaker & Fix Clean My Speaker FAQ – Audio Questions',
    description:
      'Answers to top questions about cleaning phone speakers, ejecting water with sound, and fixing muffled audio safely.',
    url: 'https://cleanmyspeaker.net/faq/',
    images: [
      {
        url: 'https://cleanmyspeaker.net/images/how-to-clean-my-speaker-fix-sound.jpg',
        width: 1024,
        height: 576,
        alt: 'Clean My Speaker & Fix Clean My Speaker FAQ Guide',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Clean My Speaker & Fix Clean My Speaker FAQ',
    description:
      'Answers to common questions about ejecting water from phone speakers and fixing muffled audio with sound waves.',
    images: ['https://cleanmyspeaker.net/images/how-to-clean-my-speaker-fix-sound.jpg'],
  },
};

const fullFaqList: FAQItem[] = [
  {
    question: 'How do I fix clean my speaker?',
    answer:
      'To fix clean my speaker online, set your phone volume to 100%, hold the speaker opening pointing downward on a dry cloth, and click "CLEAN MY SPEAKER". Let the 165 Hz resonant wave run for 30 to 60 seconds to vibrate out trapped water droplets and dust.',
  },
  {
    question: 'How do I clean my speaker?',
    answer:
      'Turn your device volume to maximum, place the phone with the speaker facing downward on a dry cloth, and click "CLEAN MY SPEAKER". Allow the 165 Hz acoustic wave to vibrate moisture and fine debris loose for 30 to 60 seconds.',
  },
  {
    question: 'How do I clean my phone speaker?',
    answer:
      'Combine acoustic vibrations with gentle surface brushing. Run the Clean My Speaker water eject cycle first to push out liquids, then lightly sweep the external holes with a clean, dry, soft-bristled toothbrush.',
  },
  {
    question: 'Can sound remove water from my speaker?',
    answer:
      'Yes. Sound waves produce mechanical vibrations in the phone speaker diaphragm. When playing low-frequency tones (around 165 Hz), high air displacement builds up behind the grille, pushing water droplets through the protective mesh.',
  },
  {
    question: 'What is the best frequency to eject water from speakers?',
    answer:
      '165 Hz is widely recognized by audio acoustic engineers (and used in smartwatch water ejection algorithms) as the optimal resonance frequency for mobile transducers. It maximizes cone excursion without damaging internal speaker coils.',
  },
  {
    question: 'Will playing loud sounds damage my smartphone speaker?',
    answer:
      'No. The audio frequencies generated by Clean My Speaker (100 Hz to 500 Hz) are calibrated within standard smartphone hardware safety tolerances. However, you should not hold the phone directly against your ear during testing.',
  },
  {
    question: 'Why does my speaker still sound muffled after running the cleaner?',
    answer:
      'If sound remains muffled after 2–3 cycles, water may have penetrated deeper into internal acoustic chambers, or compacted dirt may be blocking the grille. Let the device air-dry in a well-ventilated area for 12 hours.',
  },
  {
    question: 'Should I put my phone in rice if it got wet?',
    answer:
      'No. Never put a wet phone in rice. Rice starch, grain dust, and debris get trapped in the charging port, mic holes, and speaker mesh, turning into a sticky paste that can permanently damage internal components.',
  },
  {
    question: 'Does Clean My Speaker work on AirPods or Bluetooth headphones?',
    answer:
      'Yes! You can connect your Bluetooth earbuds or AirPods, set the volume to moderate/high, and run the sound tool to help dislodge dust or surface moisture from earbud speaker screens.',
  },
  {
    question: 'Is Clean My Speaker completely free to use?',
    answer:
      'Yes, 100% free with no hidden subscriptions, no mobile app downloads, and no registration required.',
  },
];

export default function FAQPage() {
  const breadcrumbs = [{ name: 'FAQ', href: '/faq' }];

  return (
    <div className="min-h-screen flex flex-col">
      <Header locale="en" />
      <main className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 w-full">
        <Breadcrumbs items={breadcrumbs} locale="en" />

        <article className="space-y-12 mt-6 text-slate-300">
          <header className="space-y-4 text-center">
            <div className="inline-block px-3 py-1 rounded-full bg-sky-950/80 border border-sky-500/30 text-sky-400 text-xs font-semibold uppercase tracking-wider">
              Help & Knowledge Base
            </div>
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-black text-white tracking-tight">
              Clean My Speaker FAQ: Common Questions Answered
            </h1>
            <p className="text-base sm:text-lg text-slate-300 max-w-2xl mx-auto leading-relaxed">
              Find immediate answers about water ejection, frequency tones, phone safety, and troubleshooting muffled speakers.
            </p>
          </header>

          {/* FAQ Accordion with Schema */}
          <FAQAccordion items={fullFaqList} includeSchema={true} />

          {/* Direct Link to Cleaner */}
          <section className="p-8 rounded-3xl bg-slate-900 border border-slate-800 text-center space-y-4">
            <h2 className="text-xl sm:text-2xl font-bold text-white">Ready to Clean Your Speaker?</h2>
            <p className="text-sm text-slate-300 max-w-md mx-auto">
              Experience the 165 Hz water eject tone right now directly in your mobile browser.
            </p>
            <Link
              href="/#tool"
              className="inline-block px-8 py-3.5 rounded-xl bg-sky-500 hover:bg-sky-400 text-slate-950 font-bold text-sm shadow-lg transition-transform hover:scale-103"
            >
              🔊 Launch Clean My Speaker Tool
            </Link>
          </section>

          {/* Social Sharing Callout */}
          <ShareButtons
            title="Clean My Speaker FAQ: Questions & Answers"
            description="Find answers to common questions about water ejection, 165 Hz audio frequencies, phone safety, and troubleshooting muffled speakers."
            variant="card"
          />

          {/* Dynamic Contextual Interlinking */}
          <RelatedGuides currentPath="/faq" />

          <footer className="pt-6 border-t border-slate-800 flex flex-col sm:flex-row justify-between items-center gap-4">
            <Link href="/" className="text-sky-300 underline font-semibold text-sm hover:text-sky-200">
              ← Home
            </Link>
            <Link href="/how-it-works" className="text-sky-300 underline font-semibold text-sm hover:text-sky-200">
              Learn How Sound Waves Work →
            </Link>
          </footer>
        </article>
      </main>
      <Footer locale="en" />
    </div>
  );
}
