import React from 'react';
import Link from 'next/link';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { RelatedGuides } from '@/components/RelatedGuides';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer & Hardware Safety',
  description:
    'Important disclaimer regarding acoustic speaker cleaning capabilities, physical limitations, hearing safety, and non-affiliation with smartphone manufacturers.',
  alternates: {
    canonical: 'https://cleanmyspeaker.net/disclaimer/',
  },
};

export default function DisclaimerPage() {
  const breadcrumbs = [{ name: 'Disclaimer', href: '/disclaimer' }];

  return (
    <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      <Breadcrumbs items={breadcrumbs} />

      <article className="space-y-8 mt-6 text-slate-300">
        <header className="space-y-4">
          <div className="inline-block px-3 py-1 rounded-full bg-slate-800 border border-slate-700 text-slate-300 text-xs font-semibold uppercase tracking-wider">
            Important Legal Disclosures
          </div>
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-black text-white tracking-tight">
            Disclaimer
          </h1>
          <p className="text-sm text-slate-400">
            Last Updated: August 31, 2026 • Official Website: https://cleanmyspeaker.net
          </p>
        </header>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white">1. General Information Disclaimer</h2>
          <p className="text-sm leading-relaxed">
            The information provided on <strong>Clean My Speaker</strong> (<a href="https://cleanmyspeaker.net" className="text-sky-300 underline font-semibold hover:text-sky-200">https://cleanmyspeaker.net</a>) is intended solely for general informational, educational, and utility purposes. While we strive to ensure that all information and frequency calibrations are accurate and effective, we make no representations or warranties of any kind, express or implied, regarding completeness, reliability, or suitability for any specific hardware defect.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white">2. Physical Limitations of Acoustic Cleaning</h2>
          <p className="text-sm leading-relaxed">
            Clean My Speaker relies on the mechanical movement of the speaker cone/diaphragm to produce positive air pressure waves that can displace shallow, external surface droplets and light dust from the speaker grille mesh.
          </p>
          <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800 space-y-2 text-xs sm:text-sm">
            <h3 className="font-bold text-amber-400 text-base">What Sound Waves CANNOT Do:</h3>
            <ul className="list-disc list-inside space-y-1.5 text-slate-300">
              <li>Cannot repair internal liquid intrusion that has penetrated logic boards, battery terminals, or camera modules.</li>
              <li>Cannot reverse mineral corrosion, rust, or oxidation caused by saltwater, chlorinated pool water, or long-term dampness.</li>
              <li>Cannot undo electrical short circuits caused by charging a wet device.</li>
              <li>Cannot replace blown, physically torn, or mechanically broken speaker voice coils.</li>
            </ul>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white">3. Not Professional Device Repair Advice</h2>
          <p className="text-sm leading-relaxed">
            The content and tools on this website do not constitute professional electronics repair advice or official manufacturer guidance. If your mobile device has suffered catastrophic liquid submersion, we strongly urge you to power down the device immediately and seek assistance from an authorized service provider or the original device manufacturer.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white">4. Hearing Safety & Volume Warning</h2>
          <p className="text-sm leading-relaxed">
            The audio tones generated by our cleaner include intense low-frequency sound bursts (specifically between 130 Hz and 200 Hz) played at maximum volume. To protect your hearing:
          </p>
          <ul className="list-disc list-inside space-y-1.5 text-xs sm:text-sm text-slate-400">
            <li><strong>DO NOT</strong> hold the device directly against your ear or facial region while tones are playing.</li>
            <li><strong>DO NOT</strong> use this tool with headphones, in-ear monitors (IEMs), or earbuds inserted into your ears.</li>
            <li>Keep the device away from domestic pets, infants, and individuals sensitive to loud or high-frequency sounds.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white">5. Trademark & Brand Non-Affiliation</h2>
          <p className="text-sm leading-relaxed">
            Clean My Speaker is an independent web application. Any references to brand names, models, or trademarks (including Apple, iPhone, Apple Watch, Water Lock, iOS, Samsung, Galaxy, Google, Android, Pixel, or Xiaomi) are purely descriptive to indicate device compatibility under fair use principles. Clean My Speaker is not endorsed by, sponsored by, or affiliated with Apple Inc., Google LLC, or Samsung Electronics.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white">6. Contact Us</h2>
          <p className="text-sm leading-relaxed">
            If you have questions regarding this Disclaimer, please contact us at:{' '}
            <span className="text-sky-300 font-mono">support@cleanmyspeaker.net</span>.
          </p>
        </section>

        {/* Dynamic Contextual Interlinking */}
        <RelatedGuides currentPath="/disclaimer" />

        <footer className="pt-6 border-t border-slate-800 flex justify-between items-center text-sm">
          <Link href="/" className="text-sky-300 underline font-semibold hover:text-sky-200">
            ← Return to Clean My Speaker Tool
          </Link>
          <Link href="/cookie-policy" className="text-sky-300 underline font-semibold hover:text-sky-200">
            Cookie Policy →
          </Link>
        </footer>
      </article>
    </main>
  );
}
